### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by ickc**
Edit: by the way, deriving from this repo, I created [vscode-markdown-it-pandoc](https://github.com/ickc/vscode-markdown-it-pandoc). Your copyright here is copied there as explained in the README over there. If you're interested, I can invite you as collaborator there as well.

### CODE REVIEW

**Comment by mb21** [comment]
thanks!

cool, btw. you couldn't just include this package in https://github.com/ickc/vscode-markdown-it-pandoc/blob/master/package.json instead of copying?

**Comment by ickc** [comment]
That's what I did in the beginning and didn't work. I think it may be because you're calling markdown-it directly: https://github.com/mb21/markdown-it-pandoc/blob/master/index.js#L19

**Comment by mb21** [comment]
ah yes, I see. I could publish a new version of this package that changes things like this: https://github.com/mb21/markdown-it-pandoc/pull/3

**Comment by ickc** [comment]
Probably that would work, but I'm not an experienced Javascript developer so I can't tell for sure. I'll test it once that is merged and if it works then will update the wrapper to just calling that.

**Comment by mb21** [comment]
I just published version 2.0.0 of this package and update the README accordingly... hope it works for you!

**Pull request merged**
